package com.cursosdedesarrollo;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FormularioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void formulario() {
    // Given
    driver.get("https://www.w3schools.com/howto/howto_css_contact_form.asp");
    driver.manage().window().setSize(new Dimension(2494, 1408));
    // When
    driver.findElement(By.id("accept-choices")).click();
    // 4. Manejar el <select> de country
    WebElement selectElement = driver.findElement(By.id("country"));
    Select select = new Select(selectElement);

    // Elegimos una opción por su texto visible
    select.selectByVisibleText("USA");
    select.selectByValue("usa"); // en este caso todas son usa, pero se ha puesto así para el ejemplo
    select.selectByIndex(2); // también se podría por índice 2 que sería la tercera opción
    // rellenar campos de tipo input y textarea
    driver.findElement(By.id("fname")).sendKeys("hola");
    driver.findElement(By.id("lname")).sendKeys("mundo");
    driver.findElement(By.cssSelector("textarea.test")).sendKeys("holiwi");
    // enviar el formulario haciendo click en el enlace Submit
    driver.findElement(By.linkText("Submit")).click();
  }
}

